#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 12 20:07:42 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
